version: '3'

services:
  frontend:
    build: .
    ports:
      - "4200:80"
    container_name: pean-front-container
    restart: always

networks:
  default:
    external:
      name: pean-server_default
